// components/panda/solid/src/components/ui/heading.tsx
import { mergeProps, splitProps } from 'solid-js'
import { styled, type HTMLStyledProps, type StyledComponent } from 'styled-system/jsx'
import { text, type TextVariantProps } from 'styled-system/recipes'

type As = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'

export type HeadingProps = {
  as?: As
} & TextVariantProps &
  HTMLStyledProps<As>

export const Heading = (props: HeadingProps) => {
  const mergedProps = mergeProps({ as: 'h2' }, props)
  const [localProps, rootProps] = splitProps(mergedProps, ['as'])
  const Dynamic = styled(localProps.as as As, text) as StyledComponent<As>

  return <Dynamic {...rootProps} />
}

// components/panda/react/src/components/ui/heading.tsx
import { forwardRef, useMemo } from 'react'
import { type HTMLStyledProps, type StyledComponent, styled } from 'styled-system/jsx'
import { type TextVariantProps, text } from 'styled-system/recipes'

type As = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'

export type HeadingProps = {
  as?: As
} & TextVariantProps &
  HTMLStyledProps<As>

export const Heading = forwardRef<HTMLHeadingElement, HeadingProps>((props, ref) => {
  const { as = 'h2', ...localProps } = props
  const Dynamic = useMemo(() => styled(as, text) as StyledComponent<As>, [as])

  return <Dynamic ref={ref} {...localProps} />
})

Heading.displayName = 'Heading'
