// components/solid/src/components/ui/radio-group.tsx
import { RadioGroup } from '@ark-ui/solid/radio-group'
import type { ComponentProps } from 'solid-js'
import { createStyleContext } from 'styled-system/jsx'
import { radioGroup } from 'styled-system/recipes'

const { withProvider, withContext } = createStyleContext(radioGroup)

export type RootProps = ComponentProps<typeof Root>
export type ItemProps = ComponentProps<typeof Item>

export const Root = withProvider(RadioGroup.Root, 'root')
export const RootProvider = withProvider(RadioGroup.RootProvider, 'root')
export const Indicator = withContext(RadioGroup.Indicator, 'indicator')
export const Item = withContext(RadioGroup.Item, 'item')
export const ItemControl = withContext(RadioGroup.ItemControl, 'itemControl')
export const ItemText = withContext(RadioGroup.ItemText, 'itemText')
export const Label = withContext(RadioGroup.Label, 'label')
export const ItemHiddenInput = RadioGroup.ItemHiddenInput

export { RadioGroupContext as Context } from '@ark-ui/solid/radio-group'

// components/panda/react/src/components/ui/radio-group.tsx
import { RadioGroup as ArkRadioGroup } from '@ark-ui/react/radio-group'
import type { ComponentProps } from 'react'
import { styled } from 'styled-system/jsx'
import { radioGroup } from 'styled-system/recipes'
import { createStyleContext } from '~/lib/create-style-context'

const { withProvider, withContext } = createStyleContext(radioGroup)

const Root = withProvider(styled(ArkRadioGroup.Root), 'root')
const Indicator = withContext(styled(ArkRadioGroup.Indicator), 'indicator')
const Item = withContext(styled(ArkRadioGroup.Item), 'item')
const ItemControl = withContext(styled(ArkRadioGroup.ItemControl), 'itemControl')
const ItemText = withContext(styled(ArkRadioGroup.ItemText), 'itemText')
const Label = withContext(styled(ArkRadioGroup.Label), 'label')

export { Indicator, Item, ItemControl, ItemText, Label, Root }

export interface RadioGroupRootProps extends ComponentProps<typeof Root> {}
export interface RadioGroupIndicatorProps extends ComponentProps<typeof Indicator> {}
export interface RadioGroupItemProps extends ComponentProps<typeof Item> {}
export interface RadioGroupItemControlProps extends ComponentProps<typeof ItemControl> {}
export interface RadioGroupItemTextProps extends ComponentProps<typeof ItemText> {}
export interface RadioGroupLabelProps extends ComponentProps<typeof Label> {}
