// components/solid/src/examples/number-input/controlled.tsx
import { createSignal } from 'solid-js'

import { NumberInput } from '@/components/ui'

export const App = () => {
  const [value, setValue] = createSignal('10')
  return (
    <NumberInput.Root value={value()} onValueChange={(e) => setValue(e.value)}>
      <NumberInput.Control />
      <NumberInput.Input />
    </NumberInput.Root>
  )
}

// components/react/src/examples/number-input/controlled.tsx
'use client'
import { useState } from 'react'
import { NumberInput } from '@/components/ui'

export const App = () => {
  const [value, setValue] = useState('10')
  return (
    <NumberInput.Root value={value} onValueChange={(e) => setValue(e.value)}>
      <NumberInput.Control />
      <NumberInput.Input />
    </NumberInput.Root>
  )
}
