// components/panda/solid/src/lib/create-style-context.tsx
import { createContext, useContext } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import { cx } from 'styled-system/css'
import { styled } from 'styled-system/jsx'
import type { ElementType } from 'styled-system/types'

type Props = Record<string, unknown>
type Recipe = {
  (props?: Props): Props
  splitVariantProps: (props: Props) => [Props, Props]
}
type Slot<R extends Recipe> = keyof ReturnType<R>

export const createStyleContext = <R extends Recipe>(recipe: R) => {
  const StyleContext = createContext<Record<Slot<R>, string> | null>(null)

  const withRootProvider = <P extends {}>(Component: ElementType): ((props: P) => JSX.Element) => {
    const StyledComponent = (props: P) => {
      const [variantProps, localProps] = recipe.splitVariantProps(props)
      const slotStyles = recipe(variantProps) as Record<Slot<R>, string>

      return (
        <StyleContext.Provider value={slotStyles}>
          <Component {...localProps} />
        </StyleContext.Provider>
      )
    }
    return StyledComponent
  }

  const withProvider = <P extends { class?: string }>(
    Component: ElementType,
    slot: Slot<R>,
  ): ((props: P) => JSX.Element) => {
    const StyledComponent = styled(Component)

    return (props: P) => {
      const [variantProps, localProps] = recipe.splitVariantProps(props)
      const slotStyles = recipe(variantProps) as Record<Slot<R>, string>

      return (
        <StyleContext.Provider value={slotStyles}>
          <Dynamic
            component={StyledComponent}
            {...localProps}
            class={cx(slotStyles?.[slot], props.class)}
          />
        </StyleContext.Provider>
      )
    }
  }

  const withContext = <P extends { class?: string }>(
    Component: ElementType,
    slot: Slot<R>,
  ): ((props: P) => JSX.Element) => {
    const StyledComponent = styled(Component)

    const Foo = (props: P) => {
      const slotStyles = useContext(StyleContext)
      return (
        <Dynamic
          component={StyledComponent}
          {...props}
          class={cx(slotStyles?.[slot], props.class)}
        />
      )
    }
    return Foo
  }

  return {
    withRootProvider,
    withProvider,
    withContext,
  }
}

// components/panda/vue/src/lib/create-style-context.tsx
import { type ComputedRef, computed, defineComponent, inject, provide } from 'vue'
import { styled } from '../../styled-system/jsx'
import type { ElementType } from '../../styled-system/types'

type Props = Record<string, unknown>
type Recipe = {
  (props?: Props): Props
  splitVariantProps: (props: Props) => [Props, Props]
}
type Slot<R extends Recipe> = keyof ReturnType<R>
type StyleContext<R extends Recipe> = Record<Slot<R>, string>

export const createStyleContext = <R extends Recipe>(recipe: R) => {
  const withProvider = <P,>(Component: ElementType, slot: Slot<R>) => {
    const StyledComponent = styled(Component)

    return defineComponent<P>({
      setup(props, { slots }) {
        const splittedProps = computed(() => {
          return recipe.splitVariantProps(props)
        })

        const styles = computed(() => {
          const [variantProps] = splittedProps.value
          return recipe(variantProps) as StyleContext<R>
        })

        provide('styles', styles)
        return () => (
          <StyledComponent {...splittedProps.value[1]} class={styles.value[slot]}>
            {slots.default?.()}
          </StyledComponent>
        )
      },
    })
  }

  const withContext = <P,>(Component: ElementType, slot: Slot<R>) => {
    const StyledComponent = styled(Component)

    return defineComponent<P>({
      setup(props, { slots }) {
        const slotStyles = inject<ComputedRef<StyleContext<R>>>('styles')

        return () => (
          <StyledComponent {...props} class={slotStyles?.value?.[slot]}>
            {slots.default?.()}
          </StyledComponent>
        )
      },
    })
  }

  return { withProvider, withContext }
}
