// templates/solid/solid-start/src/components/ui/styled/text.tsx
import type { ComponentProps } from 'solid-js'
import { styled } from 'styled-system/jsx'
import { type TextVariantProps, text } from 'styled-system/recipes'
import type { StyledComponent } from 'styled-system/types'

type ParagraphProps = TextVariantProps & { as?: JSX.ElementType }

export type TextProps = ComponentProps<typeof Text>
export const Text = styled('p', text) as StyledComponent<'p', ParagraphProps>

// components/react/src/components/ui/text.ts
import { styled } from '@park-ui/styled-system/jsx'
import { type TextVariantProps, text } from '@park-ui/styled-system/recipes'
import type { ComponentProps, StyledComponent } from '@park-ui/styled-system/types'

type ParagraphProps = TextVariantProps & { as?: React.ElementType }

export type TextProps = ComponentProps<typeof Text>
export const Text = styled('p', text) as StyledComponent<'p', ParagraphProps>
