// web/src/components/demos/accordion.demo.tsx
import { ChevronDownIcon } from 'lucide-react'
import { Icon } from '~/components/ui'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
  type AccordionProps,
} from '~/components/ui/accordion'

export const Demo = (props: AccordionProps) => {
  const items = ['React', 'Solid', 'Vue']
  return (
    <Accordion defaultValue={['React']} multiple {...props}>
      {items.map((item, id) => (
        <AccordionItem key={id} value={item}>
          {({ isOpen }) => (
            <>
              <AccordionTrigger>
                {item}
                <AccordionIcon isOpen={isOpen} />
              </AccordionTrigger>
              <AccordionContent>
                <div>
                  Pudding donut gummies chupa chups oat cake marzipan biscuit tart. Dessert macaroon
                  ice cream bonbon jelly. Jelly topping tiramisu halvah lollipop.
                </div>
              </AccordionContent>
            </>
          )}
        </AccordionItem>
      ))}
    </Accordion>
  )
}

const AccordionIcon = (props: { isOpen: boolean }) => {
  const iconStyles = {
    transform: props.isOpen ? 'rotate(-180deg)' : undefined,
    transition: 'transform 0.2s',
    transformOrigin: 'center',
  }
  return (
    <Icon style={iconStyles}>
      <ChevronDownIcon />
    </Icon>
  )
}

// components/solid/src/demos/accordion.demo.tsx
import { ChevronDownIcon } from 'lucide-solid'
import { For } from 'solid-js'
import { Accordion } from '~/components/ui/accordion'

export const Demo = (props: Accordion.RootProps) => {
  const items = ['React', 'Solid', 'Svelte', 'Vue']

  return (
    <Accordion.Root defaultValue={['React']} multiple {...props}>
      <For each={items}>
        {(item) => (
          <Accordion.Item value={item} disabled={item === 'Svelte'}>
            <Accordion.ItemTrigger>
              {item}
              <Accordion.ItemIndicator>
                <ChevronDownIcon />
              </Accordion.ItemIndicator>
            </Accordion.ItemTrigger>
            <Accordion.ItemContent>
              Pudding donut gummies chupa chups oat cake marzipan biscuit tart. Dessert macaroon ice
              cream bonbon jelly. Jelly topping tiramisu halvah lollipop.
            </Accordion.ItemContent>
          </Accordion.Item>
        )}
      </For>
    </Accordion.Root>
  )
}
