// components/solid/src/demos/date-picker.demo.tsx
import { CalendarIcon, ChevronLeftIcon, ChevronRightIcon } from 'lucide-solid'
import { For } from 'solid-js'
import { Button } from '~/components/ui/button'
import { DatePicker } from '~/components/ui/date-picker'
import { IconButton } from '~/components/ui/icon-button'
import { Input } from '~/components/ui/input'

export const Demo = (props: DatePicker.RootProps) => {
  return (
    <DatePicker.Root
      positioning={{ sameWidth: true }}
      startOfWeek={1}
      selectionMode="range"
      {...props}
    >
      <DatePicker.Label>Date Picker</DatePicker.Label>
      <DatePicker.Control>
        <DatePicker.Input index={0} asChild={(inputProps) => <Input {...inputProps()} />} />
        <DatePicker.Input index={1} asChild={(inputProps) => <Input {...inputProps()} />} />
        <DatePicker.Trigger
          asChild={(triggerProps) => (
            <IconButton variant="outline" aria-label="Open date picker" {...triggerProps()}>
              <CalendarIcon />
            </IconButton>
          )}
        />
      </DatePicker.Control>
      <DatePicker.Positioner>
        <DatePicker.Content>
          <DatePicker.View view="day">
            <DatePicker.Context>
              {(api) => (
                <>
                  <DatePicker.ViewControl>
                    <DatePicker.PrevTrigger
                      asChild={(triggerProps) => (
                        <IconButton variant="ghost" size="sm" {...triggerProps()}>
                          <ChevronLeftIcon />
                        </IconButton>
                      )}
                    />
                    <DatePicker.ViewTrigger
                      asChild={(triggerProps) => (
                        <Button variant="ghost" size="sm" {...triggerProps()}>
                          <DatePicker.RangeText />
                        </Button>
                      )}
                    />
                    <DatePicker.NextTrigger
                      asChild={(triggerProps) => (
                        <IconButton variant="ghost" size="sm" {...triggerProps()}>
                          <ChevronRightIcon />
                        </IconButton>
                      )}
                    />
                  </DatePicker.ViewControl>
                  <DatePicker.Table>
                    <DatePicker.TableHead>
                      <DatePicker.TableRow>
                        <For each={api().weekDays}>
                          {(weekDay) => (
                            <DatePicker.TableHeader>{weekDay.narrow}</DatePicker.TableHeader>
                          )}
                        </For>
                      </DatePicker.TableRow>
                    </DatePicker.TableHead>
                    <DatePicker.TableBody>
                      <For each={api().weeks}>
                        {(week) => (
                          <DatePicker.TableRow>
                            <For each={week}>
                              {(day) => (
                                <DatePicker.TableCell value={day}>
                                  <DatePicker.TableCellTrigger
                                    asChild={(cellProps) => (
                                      <IconButton variant="ghost" {...cellProps()}>
                                        {day.day}
                                      </IconButton>
                                    )}
                                  />
                                </DatePicker.TableCell>
                              )}
                            </For>
                          </DatePicker.TableRow>
                        )}
                      </For>
                    </DatePicker.TableBody>
                  </DatePicker.Table>
                </>
              )}
            </DatePicker.Context>
          </DatePicker.View>
          <DatePicker.View view="month">
            <DatePicker.Context>
              {(api) => (
                <>
                  <DatePicker.ViewControl>
                    <DatePicker.PrevTrigger
                      asChild={(triggerProps) => (
                        <IconButton variant="ghost" size="sm" {...triggerProps()}>
                          <ChevronLeftIcon />
                        </IconButton>
                      )}
                    />
                    <DatePicker.ViewTrigger
                      asChild={(triggerProps) => (
                        <Button variant="ghost" size="sm" {...triggerProps()}>
                          <DatePicker.RangeText />
                        </Button>
                      )}
                    />
                    <DatePicker.NextTrigger
                      asChild={(triggerProps) => (
                        <IconButton variant="ghost" size="sm" {...triggerProps()}>
                          <ChevronRightIcon />
                        </IconButton>
                      )}
                    />
                  </DatePicker.ViewControl>
                  <DatePicker.Table>
                    <DatePicker.TableBody>
                      <For each={api().getMonthsGrid({ columns: 4, format: 'short' })}>
                        {(months) => (
                          <DatePicker.TableRow>
                            <For each={months}>
                              {(month) => (
                                <DatePicker.TableCell value={month.value}>
                                  <DatePicker.TableCellTrigger
                                    asChild={(cellProps) => (
                                      <Button variant="ghost" {...cellProps()}>
                                        {month.label}
                                      </Button>
                                    )}
                                  />
                                </DatePicker.TableCell>
                              )}
                            </For>
                          </DatePicker.TableRow>
                        )}
                      </For>
                    </DatePicker.TableBody>
                  </DatePicker.Table>
                </>
              )}
            </DatePicker.Context>
          </DatePicker.View>
          <DatePicker.View view="year">
            <DatePicker.Context>
              {(api) => (
                <>
                  <DatePicker.ViewControl>
                    <DatePicker.PrevTrigger
                      asChild={(triggerProps) => (
                        <IconButton variant="ghost" size="sm" {...triggerProps()}>
                          <ChevronLeftIcon />
                        </IconButton>
                      )}
                    />
                    <DatePicker.ViewTrigger
                      asChild={(triggerProps) => (
                        <Button variant="ghost" size="sm" {...triggerProps()}>
                          <DatePicker.RangeText />
                        </Button>
                      )}
                    />
                    <DatePicker.NextTrigger
                      asChild={(triggerProps) => (
                        <IconButton variant="ghost" size="sm" {...triggerProps()}>
                          <ChevronRightIcon />
                        </IconButton>
                      )}
                    />
                  </DatePicker.ViewControl>
                  <DatePicker.Table>
                    <DatePicker.TableBody>
                      <For each={api().getYearsGrid({ columns: 4 })}>
                        {(years) => (
                          <DatePicker.TableRow>
                            <For each={years}>
                              {(year) => (
                                <DatePicker.TableCell value={year.value}>
                                  <DatePicker.TableCellTrigger
                                    asChild={(cellProps) => (
                                      <Button variant="ghost" {...cellProps()}>
                                        {year.label}
                                      </Button>
                                    )}
                                  />
                                </DatePicker.TableCell>
                              )}
                            </For>
                          </DatePicker.TableRow>
                        )}
                      </For>
                    </DatePicker.TableBody>
                  </DatePicker.Table>
                </>
              )}
            </DatePicker.Context>
          </DatePicker.View>
        </DatePicker.Content>
      </DatePicker.Positioner>
    </DatePicker.Root>
  )
}

// website/src/components/demos/date-picker.demo.tsx
import { CalendarIcon, ChevronLeftIcon, ChevronRightIcon } from 'lucide-react'
import { Button } from '~/components/ui/button'
import * as DatePicker from '~/components/ui/date-picker'
import { IconButton } from '~/components/ui/icon-button'
import { Input } from '~/components/ui/input'

export const Demo = (props: DatePicker.RootProps) => {
  return (
    <DatePicker.Root
      positioning={{ sameWidth: true }}
      startOfWeek={1}
      selectionMode="range"
      {...props}
    >
      <DatePicker.Label>Date Picker</DatePicker.Label>
      <DatePicker.Control>
        <DatePicker.Input asChild>
          <Input />
        </DatePicker.Input>
        <DatePicker.Trigger asChild>
          <IconButton variant="outline" aria-label="Open date picker">
            <CalendarIcon />
          </IconButton>
        </DatePicker.Trigger>
      </DatePicker.Control>
      <DatePicker.Positioner>
        <DatePicker.Content>
          <DatePicker.View view="day">
            {(api) => (
              <>
                <DatePicker.ViewControl>
                  <DatePicker.PrevTrigger asChild>
                    <IconButton variant="ghost" size="sm">
                      <ChevronLeftIcon />
                    </IconButton>
                  </DatePicker.PrevTrigger>
                  <DatePicker.ViewTrigger asChild>
                    <Button variant="ghost" size="sm">
                      <DatePicker.RangeText />
                    </Button>
                  </DatePicker.ViewTrigger>
                  <DatePicker.NextTrigger asChild>
                    <IconButton variant="ghost" size="sm">
                      <ChevronRightIcon />
                    </IconButton>
                  </DatePicker.NextTrigger>
                </DatePicker.ViewControl>
                <DatePicker.Table>
                  <DatePicker.TableHead>
                    <DatePicker.TableRow>
                      {api.weekDays.map((weekDay, id) => (
                        <DatePicker.TableHeader key={id}>{weekDay.narrow}</DatePicker.TableHeader>
                      ))}
                    </DatePicker.TableRow>
                  </DatePicker.TableHead>
                  <DatePicker.TableBody>
                    {api.weeks.map((week, id) => (
                      <DatePicker.TableRow key={id}>
                        {week.map((day, id) => (
                          <DatePicker.TableCell key={id} value={day}>
                            <DatePicker.TableCellTrigger asChild>
                              <IconButton variant="ghost">{day.day}</IconButton>
                            </DatePicker.TableCellTrigger>
                          </DatePicker.TableCell>
                        ))}
                      </DatePicker.TableRow>
                    ))}
                  </DatePicker.TableBody>
                </DatePicker.Table>
              </>
            )}
          </DatePicker.View>
          <DatePicker.View view="month">
            {(api) => (
              <>
                <DatePicker.ViewControl>
                  <DatePicker.PrevTrigger asChild>
                    <IconButton variant="ghost" size="sm">
                      <ChevronLeftIcon />
                    </IconButton>
                  </DatePicker.PrevTrigger>
                  <DatePicker.ViewTrigger asChild>
                    <Button variant="ghost" size="sm">
                      <DatePicker.RangeText />
                    </Button>
                  </DatePicker.ViewTrigger>
                  <DatePicker.NextTrigger asChild>
                    <IconButton variant="ghost" size="sm">
                      <ChevronRightIcon />
                    </IconButton>
                  </DatePicker.NextTrigger>
                </DatePicker.ViewControl>
                <DatePicker.Table>
                  <DatePicker.TableBody>
                    {api.getMonthsGrid({ columns: 4, format: 'short' }).map((months, id) => (
                      <DatePicker.TableRow key={id}>
                        {months.map((month, id) => (
                          <DatePicker.TableCell key={id} value={month.value}>
                            <DatePicker.TableCellTrigger asChild>
                              <Button variant="ghost">{month.label}</Button>
                            </DatePicker.TableCellTrigger>
                          </DatePicker.TableCell>
                        ))}
                      </DatePicker.TableRow>
                    ))}
                  </DatePicker.TableBody>
                </DatePicker.Table>
              </>
            )}
          </DatePicker.View>
          <DatePicker.View view="year">
            {(api) => (
              <>
                <DatePicker.ViewControl>
                  <DatePicker.PrevTrigger asChild>
                    <IconButton variant="ghost" size="sm">
                      <ChevronLeftIcon />
                    </IconButton>
                  </DatePicker.PrevTrigger>
                  <DatePicker.ViewTrigger asChild>
                    <Button variant="ghost" size="sm">
                      <DatePicker.RangeText />
                    </Button>
                  </DatePicker.ViewTrigger>
                  <DatePicker.NextTrigger asChild>
                    <IconButton variant="ghost" size="sm">
                      <ChevronRightIcon />
                    </IconButton>
                  </DatePicker.NextTrigger>
                </DatePicker.ViewControl>
                <DatePicker.Table>
                  <DatePicker.TableBody>
                    {api.getYearsGrid({ columns: 4 }).map((years, id) => (
                      <DatePicker.TableRow key={id}>
                        {years.map((year, id) => (
                          <DatePicker.TableCell key={id} value={year.value}>
                            <DatePicker.TableCellTrigger asChild>
                              <Button variant="ghost">{year.label}</Button>
                            </DatePicker.TableCellTrigger>
                          </DatePicker.TableCell>
                        ))}
                      </DatePicker.TableRow>
                    ))}
                  </DatePicker.TableBody>
                </DatePicker.Table>
              </>
            )}
          </DatePicker.View>
        </DatePicker.Content>
      </DatePicker.Positioner>
    </DatePicker.Root>
  )
}
