// components/solid/src/demos/editable.demo.tsx
import { Show } from 'solid-js'
import { Button } from '~/components/ui/button'
import { Editable } from '~/components/ui/editable'
import { FormLabel } from '~/components/ui/form-label'

export const Demo = (props: Editable.RootProps) => {
  return (
    <Editable.Root
      placeholder="Your favorite Framework"
      defaultValue="Double click to edit"
      activationMode="dblclick"
      {...props}
    >
      <Editable.Label
        asChild={(labelProps) => <FormLabel {...labelProps()}>Framework</FormLabel>}
      />
      <Editable.Area>
        <Editable.Input />
        <Editable.Preview />
      </Editable.Area>
      <Editable.Context>
        {(editable) => (
          <Editable.Control>
            <Show
              when={editable().editing}
              fallback={
                <Editable.EditTrigger
                  asChild={(triggerProps) => (
                    <Button {...triggerProps()} variant="link">
                      Edit
                    </Button>
                  )}
                />
              }
            >
              <>
                <Editable.SubmitTrigger
                  asChild={(triggerProps) => (
                    <Button {...triggerProps()} variant="link">
                      Save
                    </Button>
                  )}
                />
                <Editable.CancelTrigger
                  asChild={(triggerProps) => (
                    <Button {...triggerProps()} variant="link">
                      Cancel
                    </Button>
                  )}
                />
              </>
            </Show>
          </Editable.Control>
        )}
      </Editable.Context>
    </Editable.Root>
  )
}

// website/src/components/demos/editable.demo.tsx
import { Button } from '~/components/ui/button'
import * as Editable from '~/components/ui/editable'
import { FormLabel } from '~/components/ui/form-label'

export const Demo = (props: Editable.RootProps) => {
  return (
    <Editable.Root
      placeholder="Your favorite Framework"
      defaultValue="Double click to edit"
      activationMode="dblclick"
      {...props}
    >
      <Editable.Label asChild>
        <FormLabel>Framework</FormLabel>
      </Editable.Label>
      <Editable.Area>
        <Editable.Input />
        <Editable.Preview />
      </Editable.Area>
      <Editable.Context>
        {(editable) => (
          <Editable.Control>
            {editable.editing ? (
              <>
                <Editable.SubmitTrigger asChild>
                  <Button variant="link">Save</Button>
                </Editable.SubmitTrigger>
                <Editable.CancelTrigger asChild>
                  <Button variant="link">Cancel</Button>
                </Editable.CancelTrigger>
              </>
            ) : (
              <Editable.EditTrigger asChild>
                <Button variant="link">Edit</Button>
              </Editable.EditTrigger>
            )}
          </Editable.Control>
        )}
      </Editable.Context>
    </Editable.Root>
  )
}
