// website/src/components/ui/select.tsx
'use client'

import type { Assign } from '@ark-ui/react'
import { Select } from '@ark-ui/react/select'
import { type SelectVariantProps, select } from 'styled-system/recipes'
import type { JsxStyleProps } from 'styled-system/types'
import { createStyleContext } from '~/lib/create-style-context'

const { withProvider, withContext } = createStyleContext(select)

export interface RootProps
  extends Assign<JsxStyleProps, Select.RootProps<Select.CollectionItem>>,
    SelectVariantProps {}
export const Root = withProvider<HTMLDivElement, RootProps>(Select.Root, 'root')

export const ClearTrigger = withContext<
  HTMLButtonElement,
  Assign<JsxStyleProps, Select.ClearTriggerProps>
>(Select.ClearTrigger, 'clearTrigger')

export const Content = withContext<HTMLDivElement, Assign<JsxStyleProps, Select.ContentProps>>(
  Select.Content,
  'content',
)

export const Control = withContext<HTMLDivElement, Assign<JsxStyleProps, Select.ControlProps>>(
  Select.Control,
  'control',
)

export const Indicator = withContext<HTMLDivElement, Assign<JsxStyleProps, Select.IndicatorProps>>(
  Select.Indicator,
  'indicator',
)

export const ItemGroupLabel = withContext<
  HTMLDivElement,
  Assign<JsxStyleProps, Select.ItemGroupLabelProps>
>(Select.ItemGroupLabel, 'itemGroupLabel')

export const ItemGroup = withContext<HTMLDivElement, Assign<JsxStyleProps, Select.ItemGroupProps>>(
  Select.ItemGroup,
  'itemGroup',
)

export const ItemIndicator = withContext<
  HTMLDivElement,
  Assign<JsxStyleProps, Select.ItemIndicatorProps>
>(Select.ItemIndicator, 'itemIndicator')

export const Item = withContext<HTMLDivElement, Assign<JsxStyleProps, Select.ItemProps>>(
  Select.Item,
  'item',
)

export const ItemText = withContext<HTMLDivElement, Assign<JsxStyleProps, Select.ItemTextProps>>(
  Select.ItemText,
  'itemText',
)

export const Label = withContext<HTMLLabelElement, Assign<JsxStyleProps, Select.LabelProps>>(
  Select.Label,
  'label',
)

export const Positioner = withContext<
  HTMLDivElement,
  Assign<JsxStyleProps, Select.PositionerProps>
>(Select.Positioner, 'positioner')

export const Trigger = withContext<HTMLButtonElement, Assign<JsxStyleProps, Select.TriggerProps>>(
  Select.Trigger,
  'trigger',
)

export const ValueText = withContext<HTMLSpanElement, Assign<JsxStyleProps, Select.ValueTextProps>>(
  Select.ValueText,
  'valueText',
)

export {
  SelectContext as Context,
  SelectHiddenSelect as HiddenSelect,
  type SelectContextProps as ContextProps,
  type SelectHiddenSelectProps as HiddenSelectProps,
} from '@ark-ui/react/select'

// templates/solid/solid-start/src/components/ui/primitives/select.tsx
import { type Assign, Select } from '@ark-ui/solid'
import type { ComponentProps } from 'solid-js'
import { type SelectVariantProps, select } from 'styled-system/recipes'
import type { HTMLStyledProps } from 'styled-system/types'
import { createStyleContext } from '~/lib/create-style-context'

const { withRootProvider, withContext } = createStyleContext(select)

export type RootProviderProps = ComponentProps<typeof RootProvider>
export const RootProvider = withRootProvider<
  Assign<
    Assign<HTMLStyledProps<'div'>, Select.RootProviderBaseProps<Select.CollectionItem>>,
    SelectVariantProps
  >
>(Select.RootProvider)

export type RootProps = ComponentProps<typeof Root>
export const Root = withRootProvider<
  Assign<
    Assign<HTMLStyledProps<'div'>, Select.RootBaseProps<Select.CollectionItem>>,
    SelectVariantProps
  >
>(Select.Root)

export const ClearTrigger = withContext<
  Assign<HTMLStyledProps<'button'>, Select.ClearTriggerProps>
>(Select.ClearTrigger, 'clearTrigger')

export const Content = withContext<Assign<HTMLStyledProps<'div'>, Select.ContentProps>>(
  Select.Content,
  'content',
)

export const Control = withContext<Assign<HTMLStyledProps<'div'>, Select.ControlProps>>(
  Select.Control,
  'control',
)

export const Indicator = withContext<Assign<HTMLStyledProps<'div'>, Select.IndicatorProps>>(
  Select.Indicator,
  'indicator',
)

export const ItemGroupLabel = withContext<
  Assign<HTMLStyledProps<'div'>, Select.ItemGroupLabelProps>
>(Select.ItemGroupLabel, 'itemGroupLabel')

export const ItemGroup = withContext<Assign<HTMLStyledProps<'div'>, Select.ItemGroupProps>>(
  Select.ItemGroup,
  'itemGroup',
)

export const ItemIndicator = withContext<Assign<HTMLStyledProps<'div'>, Select.ItemIndicatorProps>>(
  Select.ItemIndicator,
  'itemIndicator',
)

export const Item = withContext<Assign<HTMLStyledProps<'div'>, Select.ItemProps>>(
  Select.Item,
  'item',
)

export const ItemText = withContext<Assign<HTMLStyledProps<'span'>, Select.ItemTextProps>>(
  Select.ItemText,
  'itemText',
)

export const Label = withContext<Assign<HTMLStyledProps<'label'>, Select.LabelProps>>(
  Select.Label,
  'label',
)

export const List = withContext<Assign<HTMLStyledProps<'div'>, Select.ListProps>>(
  Select.List,
  'list',
)

export const Positioner = withContext<Assign<HTMLStyledProps<'div'>, Select.PositionerProps>>(
  Select.Positioner,
  'positioner',
)

export const Trigger = withContext<Assign<HTMLStyledProps<'button'>, Select.TriggerProps>>(
  Select.Trigger,
  'trigger',
)

export const ValueText = withContext<Assign<HTMLStyledProps<'span'>, Select.ValueTextProps>>(
  Select.ValueText,
  'valueText',
)

export {
  SelectContext as Context,
  SelectHiddenSelect as HiddenSelect,
} from '@ark-ui/solid'
