// components/react/src/examples/radio-group/closed.tsx
import { forwardRef, type InputHTMLAttributes } from 'react'
import * as StyledRadioGroup from '@/components/ui/radio-group'

export interface RadioProps extends StyledRadioGroup.ItemProps {
  inputProps?: InputHTMLAttributes<HTMLInputElement>
}

export const Radio = forwardRef<HTMLInputElement, RadioProps>(function Radio(props, ref) {
  const { children, inputProps, ...rest } = props
  return (
    <StyledRadioGroup.Item {...rest}>
      <StyledRadioGroup.ItemHiddenInput ref={ref} {...inputProps} />
      <StyledRadioGroup.ItemControl />
      {children && <StyledRadioGroup.ItemText>{children}</StyledRadioGroup.ItemText>}
    </StyledRadioGroup.Item>
  )
})

export const RadioGroup = StyledRadioGroup.Root

// components/solid/src/examples/radio-group/closed.tsx
import { type ComponentProps, type JSX, splitProps } from 'solid-js'
import * as StyledRadioGroup from '@/components/ui/radio-group'

export interface RadioProps extends StyledRadioGroup.ItemProps {
  inputProps?: ComponentProps<typeof StyledRadioGroup.ItemHiddenInput>
  children?: JSX.Element
}

export const Radio = (props: RadioProps) => {
  const [local, rest] = splitProps(props, ['children', 'inputProps'])

  return (
    <StyledRadioGroup.Item {...rest}>
      <StyledRadioGroup.ItemHiddenInput {...local.inputProps} />
      <StyledRadioGroup.ItemControl />
      {local.children && <StyledRadioGroup.ItemText>{local.children}</StyledRadioGroup.ItemText>}
    </StyledRadioGroup.Item>
  )
}

export const RadioGroup = StyledRadioGroup.Root
