// components/react/src/examples/radio-group/disabled.tsx
import { RadioGroup } from '@/components/ui'

export const App = () => {
  return (
    <RadioGroup.Root defaultValue="react">
      {items.map((item) => (
        <RadioGroup.Item key={item.value} value={item.value} disabled={item.disabled}>
          <RadioGroup.ItemHiddenInput />
          <RadioGroup.ItemControl />
          <RadioGroup.ItemText>{item.label}</RadioGroup.ItemText>
        </RadioGroup.Item>
      ))}
    </RadioGroup.Root>
  )
}

const items = [
  { label: 'React', value: 'react' },
  { label: 'Solid', value: 'solid' },
  { label: 'Vue', value: 'vue' },
  { label: 'Svelte', value: 'svelte', disabled: true },
]

// components/solid/src/examples/radio-group/disabled.tsx
import { For } from 'solid-js'
import { RadioGroup } from '@/components/ui'

export const App = () => {
  return (
    <RadioGroup.Root defaultValue="react">
      <For each={items}>
        {(item) => (
          <RadioGroup.Item value={item.value} disabled={item.disabled}>
            <RadioGroup.ItemHiddenInput />
            <RadioGroup.ItemControl />
            <RadioGroup.ItemText>{item.label}</RadioGroup.ItemText>
          </RadioGroup.Item>
        )}
      </For>
    </RadioGroup.Root>
  )
}

const items = [
  { label: 'React', value: 'react' },
  { label: 'Solid', value: 'solid' },
  { label: 'Vue', value: 'vue' },
  { label: 'Svelte', value: 'svelte', disabled: true },
]
