// website/src/components/ui/slider.tsx
'use client'
import type { Assign } from '@ark-ui/react'
import { Slider as ArkSlider, type SliderRootProps } from '@ark-ui/react/slider'
import { type ReactNode, forwardRef } from 'react'
import { css, cx } from 'styled-system/css'
import { splitCssProps } from 'styled-system/jsx'
import { type SliderVariantProps, slider } from 'styled-system/recipes'
import type { JsxStyleProps } from 'styled-system/types'

export interface SliderProps extends Assign<JsxStyleProps, SliderRootProps>, SliderVariantProps {
  marks?: {
    value: number
    label?: ReactNode
  }[]
}

export const Slider = forwardRef<HTMLDivElement, SliderProps>((props, ref) => {
  const [variantProps, sliderProps] = slider.splitVariantProps(props)
  const [cssProps, localProps] = splitCssProps(sliderProps)
  const { children, className, ...rootProps } = localProps
  const styles = slider(variantProps)

  return (
    <ArkSlider.Root ref={ref} className={cx(styles.root, css(cssProps), className)} {...rootProps}>
      <ArkSlider.Context>
        {(api) => (
          <>
            {children && <ArkSlider.Label className={styles.label}>{children}</ArkSlider.Label>}
            <ArkSlider.Control className={styles.control}>
              <ArkSlider.Track className={styles.track}>
                <ArkSlider.Range className={styles.range} />
              </ArkSlider.Track>
              {api.value.map((_, index) => (
                <ArkSlider.Thumb key={index} index={index} className={styles.thumb} />
              ))}
            </ArkSlider.Control>
            {props.marks && (
              <ArkSlider.MarkerGroup className={styles.markerGroup}>
                {props.marks.map((mark) => (
                  <ArkSlider.Marker key={mark.value} value={mark.value} className={styles.marker}>
                    {mark.label}
                  </ArkSlider.Marker>
                ))}
              </ArkSlider.MarkerGroup>
            )}
          </>
        )}
      </ArkSlider.Context>
    </ArkSlider.Root>
  )
})

Slider.displayName = 'Slider'

// components/solid/src/components/ui/slider.tsx
import { Slider as ArkSlider, type Assign, type SliderRootProps } from '@ark-ui/solid'
import { Index, type JSX, Show, children, splitProps } from 'solid-js'
import { css, cx } from 'styled-system/css'
import { splitCssProps } from 'styled-system/jsx'
import { type SliderVariantProps, slider } from 'styled-system/recipes'
import type { JsxStyleProps } from 'styled-system/types'

export interface SliderProps extends Assign<JsxStyleProps, SliderRootProps>, SliderVariantProps {
  marks?: {
    value: number
    label?: JSX.Element
  }[]
}

export const Slider = (props: SliderProps) => {
  const [variantProps, ratingGroupProps] = slider.splitVariantProps(props)
  const [cssProps, elementProps] = splitCssProps(ratingGroupProps)
  const [localProps, rootProps] = splitProps(elementProps, ['children', 'class', 'marks'])
  const getChildren = children(() => localProps.children)
  const styles = slider(variantProps)

  return (
    <ArkSlider.Root class={cx(styles.root, css(cssProps), localProps.class)} {...rootProps}>
      <ArkSlider.Context>
        {(api) => (
          <>
            <Show when={getChildren()}>
              <ArkSlider.Label class={styles.label}>{getChildren()}</ArkSlider.Label>
            </Show>
            <ArkSlider.Control class={styles.control}>
              <ArkSlider.Track class={styles.track}>
                <ArkSlider.Range class={styles.range} />
              </ArkSlider.Track>
              <Index each={api().value}>
                {(_, index) => <ArkSlider.Thumb index={index} class={styles.thumb} />}
              </Index>
            </ArkSlider.Control>
            <Show when={localProps.marks}>
              <ArkSlider.MarkerGroup class={styles.markerGroup}>
                <Index each={localProps.marks}>
                  {(mark) => (
                    <ArkSlider.Marker value={mark().value} class={styles.marker}>
                      {mark().label}
                    </ArkSlider.Marker>
                  )}
                </Index>
              </ArkSlider.MarkerGroup>
            </Show>
          </>
        )}
      </ArkSlider.Context>
    </ArkSlider.Root>
  )
}
