// components/tailwind/react/src/components/ui/code.tsx
import { ark, type HTMLArkProps } from '@ark-ui/react/factory'
import { forwardRef } from 'react'
import { tv, type VariantProps } from 'tailwind-variants'

export interface CodeProps extends CodeVariantProps, HTMLArkProps<'code'> {}

export const Code = forwardRef<HTMLElement, CodeProps>((props, ref) => {
  const { size, variant, className, ...rest } = props
  return <ark.code className={styles({ size, variant, className })} ref={ref} {...rest} />
})

Code.displayName = 'Code'

type CodeVariantProps = VariantProps<typeof styles>

const styles = tv(
  {
    base: 'code',
    defaultVariants: { size: 'md', variant: 'outline' },
    variants: {
      variant: { outline: 'code--variant_outline', ghost: 'code--variant_ghost' },
      size: { sm: 'code--size_sm', md: 'code--size_md', lg: 'code--size_lg' },
    },
  },
  { twMerge: false },
)

// components/tailwind/solid/src/components/ui/code.tsx
import { type HTMLArkProps, ark } from '@ark-ui/solid'
import { splitProps } from 'solid-js'
import { type VariantProps, tv } from 'tailwind-variants'

export interface CodeProps extends CodeVariantProps, HTMLArkProps<'code'> {}

export const Code = (props: CodeProps) => {
  const [variantProps, codeProps] = splitProps(props, ['class', 'size'])
  return <ark.code class={styles(variantProps)} {...codeProps} />
}

type CodeVariantProps = VariantProps<typeof styles>

const styles = tv(
  {
    base: 'code',
    defaultVariants: { size: 'md', variant: 'outline' },
    variants: {
      variant: { outline: 'code--variant_outline', ghost: 'code--variant_ghost' },
      size: { sm: 'code--size_sm', md: 'code--size_md', lg: 'code--size_lg' },
    },
  },
  { twMerge: false },
)
