// components/solid/src/components/ui/primitives/carousel.tsx
import { Carousel, type Assign } from '@ark-ui/solid'
import type { ComponentProps } from 'solid-js'
import { type CarouselVariantProps, carousel } from 'styled-system/recipes'
import type { HTMLStyledProps } from 'styled-system/types'
import { createStyleContext } from '~/lib/create-style-context'

const { withProvider, withContext } = createStyleContext(carousel)

export type RootProviderProps = ComponentProps<typeof RootProvider>
export const RootProvider = withProvider<
  Assign<Assign<HTMLStyledProps<'div'>, Carousel.RootProviderProps>, CarouselVariantProps>
>(Carousel.RootProvider, 'root')

export type RootProps = ComponentProps<typeof Root>
export const Root = withProvider<
  Assign<Assign<HTMLStyledProps<'div'>, Carousel.RootProps>, CarouselVariantProps>
>(Carousel.Root, 'root')

export const Control = withContext<Assign<HTMLStyledProps<'div'>, Carousel.ControlProps>>(
  Carousel.Control,
  'control',
)

export const IndicatorGroup = withContext<
  Assign<HTMLStyledProps<'div'>, Carousel.IndicatorGroupProps>
>(Carousel.IndicatorGroup, 'indicatorGroup')

export const Indicator = withContext<Assign<HTMLStyledProps<'button'>, Carousel.IndicatorProps>>(
  Carousel.Indicator,
  'indicator',
)

export const ItemGroup = withContext<Assign<HTMLStyledProps<'div'>, Carousel.ItemGroupProps>>(
  Carousel.ItemGroup,
  'itemGroup',
)

export const Item = withContext<Assign<HTMLStyledProps<'div'>, Carousel.ItemProps>>(
  Carousel.Item,
  'item',
)

export const NextTrigger = withContext<
  Assign<HTMLStyledProps<'button'>, Carousel.NextTriggerProps>
>(Carousel.NextTrigger, 'nextTrigger')

export const PrevTrigger = withContext<
  Assign<HTMLStyledProps<'button'>, Carousel.PrevTriggerProps>
>(Carousel.PrevTrigger, 'prevTrigger')

export const Viewport = withContext<Assign<HTMLStyledProps<'div'>, Carousel.ViewportProps>>(
  Carousel.Viewport,
  'viewport',
)

export { CarouselContext as Context } from '@ark-ui/solid'

// website/src/components/ui/carousel.tsx
'use client'

import type { Assign } from '@ark-ui/react'
import { Carousel } from '@ark-ui/react/carousel'
import { type CarouselVariantProps, carousel } from 'styled-system/recipes'
import type { JsxStyleProps } from 'styled-system/types'
import { createStyleContext } from '~/lib/create-style-context'

const { withProvider, withContext } = createStyleContext(carousel)

export interface RootProps
  extends Assign<JsxStyleProps, Carousel.RootProps>,
    CarouselVariantProps {}
export const Root = withProvider<HTMLDivElement, RootProps>(Carousel.Root, 'root')

export const Control = withContext<HTMLDivElement, Assign<JsxStyleProps, Carousel.ControlProps>>(
  Carousel.Control,
  'control',
)

export const IndicatorGroup = withContext<
  HTMLDivElement,
  Assign<JsxStyleProps, Carousel.IndicatorGroupProps>
>(Carousel.IndicatorGroup, 'indicatorGroup')

export const Indicator = withContext<
  HTMLButtonElement,
  Assign<JsxStyleProps, Carousel.IndicatorProps>
>(Carousel.Indicator, 'indicator')

export const ItemGroup = withContext<
  HTMLDivElement,
  Assign<JsxStyleProps, Carousel.ItemGroupProps>
>(Carousel.ItemGroup, 'itemGroup')

export const Item = withContext<HTMLDivElement, Assign<JsxStyleProps, Carousel.ItemProps>>(
  Carousel.Item,
  'item',
)

export const NextTrigger = withContext<
  HTMLButtonElement,
  Assign<JsxStyleProps, Carousel.NextTriggerProps>
>(Carousel.NextTrigger, 'nextTrigger')

export const PrevTrigger = withContext<
  HTMLButtonElement,
  Assign<JsxStyleProps, Carousel.PrevTriggerProps>
>(Carousel.PrevTrigger, 'prevTrigger')

export const Viewport = withContext<HTMLDivElement, Assign<JsxStyleProps, Carousel.ViewportProps>>(
  Carousel.Viewport,
  'viewport',
)

export {
  CarouselContext as Context,
  type CarouselContextProps as ContextProps,
} from '@ark-ui/react/carousel'
